language: c
fast_finish: true

os:
  - linux
  - osx

env: FC=gfortran

dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc;
      brew install openblas;
    fi

install:
  - cd bin
  - cmake ..

script:
    - make

