language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages:
    - gfortran
    - libopenblas-dev

matrix:
  include:
  - os: linux
  - os: osx
    before_install:
    - brew install gcc > /dev/null
    - brew install openblas > /dev/null
  - os: windows
    install:
    - cd build
    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    - cmake --build .
    script: ctest -E HornSchunck --output-on-failure

install:
- cd build
- cmake ..
- cmake --build .

script: ctest --output-on-failure
